/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.m3u8.download.video.gui.UI;

import com.m3u8.bean.po.Settings;
import com.m3u8.config.SpringUtil;
import com.m3u8.download.video.gui.utils.MyFileChooser;
import com.m3u8.download.video.gui.utils.dialog.DialogUtil;
import com.m3u8.download.video.m3u8.utils.StringUtils;
import com.m3u8.service.SettingsService;

import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;

/**
 *
 * @author xiaotian
 */
public class SettingPage extends javax.swing.JFrame {

    private SettingsService settingsService = SpringUtil.getBean(SettingsService.class);

    private  Settings settings = settingsService.selectSetting();
    /**
     * Creates new form SettingPage
     */
    public SettingPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        coreLider = new javax.swing.JSlider();
        coreNumerText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        saveAsBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        downloadedDelete = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        downloadedForExitBtn = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        atTimeBtn = new javax.swing.JComboBox<>();
        defaultSaveFileChooser = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        reminderAfterDownloadBtn = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        openImgByCustom = new javax.swing.JButton();
        setKey = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        determineBtn = new javax.swing.JButton();
        customBackgroudComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        defaultSaveTempFileChooser = new javax.swing.JComboBox<>();
        saveTempAsBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel1.setText("下载核心数");

        coreLider.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        coreLider.setMinimum(1);
        coreLider.setMaximum(100);
        coreLider.setValue(settings.getDownloadCores());
        coreLider.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                JSlider source = (JSlider) e.getSource();
                if (!source.getValueIsAdjusting()) {
                    int value = source.getValue();
                    // 处理滑动事件，获取滑动后的值
                    coreNumerText.setText(String.valueOf(source.getValue()));
                }

            }
        });

        coreNumerText.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        coreNumerText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        coreNumerText.setText(settings.getDownloadCores() + "");
        coreNumerText.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        coreNumerText.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {

            }

            @Override
            public void removeUpdate(DocumentEvent e) {

            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                // 值改变
                String text = coreNumerText.getText();
                try {
                    coreLider.setValue(Integer.parseInt(text));
                } catch (Exception ex) {
                    DialogUtil.showCustomDialog("核心数输入值有误", "核心数只能输入整数，且值只能再1~100之间");
                }

            }
        });

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel2.setText("默认文件保存位置");

        saveAsBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        saveAsBtn.setIcon(new javax.swing.ImageIcon("static/icon/转换文件夹1_folder-conversion-one.png")); // NOI18N
        saveAsBtn.setText("打开");
        saveAsBtn.setPreferredSize(new java.awt.Dimension(89, 26));
        saveAsBtn.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                MyFileChooser.fileChooserByDir(
                        StringUtils.isBlank(defaultSaveFileChooser.getItemAt(0))
                                ? System.getProperty("user.dir")
                                : defaultSaveFileChooser.getItemAt(0));

                //todo 保存到数据库
            }
        });

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel3.setText("下载文件后在记录里删除");

        downloadedDelete.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        downloadedDelete.setText("删除");
        downloadedDelete.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                boolean selected = downloadedDelete.isSelected();
            }
        });

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel4.setText("下载完成后自动退出");

        downloadedForExitBtn.setText("退出");
        downloadedForExitBtn.setSelected(settings.getAutoExitAfterDownload());
        downloadedForExitBtn.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                boolean selected = downloadedDelete.isSelected();
                settings.setAutoExitAfterDownload(selected);
            }
        });

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel5.setText("定时下载，现在不下载");

        atTimeBtn.setEditable(true);
        atTimeBtn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10 分钟", "30 分钟", "1   小时", "1   小时 30 分钟", "2   小时", "3   小时", "4   小时" }));
        atTimeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {

            }
        });

        defaultSaveFileChooser.setEditable(true);
        defaultSaveFileChooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { settings.getDefaultSaveFolder()  }));
        String defaultSaveFolder = settings.getDefaultSaveFolder();
        if(StringUtils.isBlank(defaultSaveFolder) ){
            defaultSaveFolder = System.getProperty("user.home");
        }
        defaultSaveFileChooser.setSelectedItem(defaultSaveFolder);

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel6.setText("下载完成后提醒我");

        reminderAfterDownloadBtn.setText("是");

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel7.setText("设置软件背景");

        openImgByCustom.setIcon(new javax.swing.ImageIcon("static/icon/切换主题_switch-themes.png")); // NOI18N
        openImgByCustom.setText("打开文件");
        openImgByCustom.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                String s = MyFileChooser.fileChooser(MyFileChooser.IMG);
                File file = new File(s);
                if(!file.exists()){
                    DialogUtil.showCustomDialog("错误", "未找到对应的图像位置", "确定");
                }
                settings.setBackground(s);
                DialogUtil.showCustomDialog("提醒", "下回启动会自动更换该背景", "确定");
            }
        });

        setKey.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        setKey.setText("设置快捷键");
        setKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setKeyActionPerformed(evt);
            }
        });

        cancelBtn.setText("取消");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        determineBtn.setText("确定");
        determineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                determineBtnActionPerformed(evt);
            }
        });

        customBackgroudComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F:/m3u8" }));

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel8.setText("默认临时目录位置");

        defaultSaveTempFileChooser.setEditable(true);
        defaultSaveTempFileChooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {settings.getDefaultTempFolder()}));

        saveTempAsBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        saveTempAsBtn.setIcon(new javax.swing.ImageIcon("static/icon/转换文件夹1_folder-conversion-one.png")); // NOI18N
        saveTempAsBtn.setText("打开");
        saveTempAsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                String save = MyFileChooser.fileChooserBySaveFile("save");
                if(null == save){
                    return;
                }
                defaultSaveTempFileChooser.setSelectedItem(save);
                defaultSaveTempFileChooser.addItem(save);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(determineBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancelBtn)
                                .addGap(18, 18, 18))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(atTimeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(292, 292, 292))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(customBackgroudComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(40, 40, 40)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(setKey)
                                                        .addComponent(openImgByCustom, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(104, 104, 104))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(66, 66, 66)
                                                                .addComponent(reminderAfterDownloadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(37, 37, 37)
                                                                .addComponent(downloadedDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(61, 61, 61)
                                                                .addComponent(downloadedForExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(coreNumerText, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                .addComponent(coreLider, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                                .addGap(34, 34, 34)
                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(defaultSaveFileChooser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                        .addComponent(defaultSaveTempFileChooser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(saveAsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(saveTempAsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                                .addGap(40, 40, 40))))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(coreLider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(coreNumerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(defaultSaveFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(saveAsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(defaultSaveTempFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(saveTempAsBtn))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(downloadedDelete))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(downloadedForExitBtn))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(atTimeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(reminderAfterDownloadBtn))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(openImgByCustom, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(customBackgroudComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(setKey, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(determineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 607, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 487, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        com.m3u8.download.video.gui.utils.PositionAndStyleSetting.windowCentered(this);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }// </editor-fold>

    private void setKeyActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false);
    }

    private void determineBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // 确定
        int core = Integer.parseInt(coreNumerText.getText());
        String defaultSaveTempFileChooserSelectedItem = (String) defaultSaveTempFileChooser.getSelectedItem();
        String saveFileChooserSelectedItem = (String) defaultSaveFileChooser.getSelectedItem();
        String backgroudComboBoxSelectedItem = (String)customBackgroudComboBox.getSelectedItem();

        settings.setDownloadCores(core);
        settings.setDefaultTempFolder(defaultSaveTempFileChooserSelectedItem);
        settings.setDefaultSaveFolder(saveFileChooserSelectedItem);
        settings.setBackground(backgroudComboBoxSelectedItem);

        settingsService.updateSetting(settings);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SettingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SettingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SettingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SettingPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JComboBox<String> atTimeBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JSlider coreLider;
    private javax.swing.JTextField coreNumerText;
    private javax.swing.JComboBox<String> customBackgroudComboBox;
    private javax.swing.JComboBox<String> defaultSaveFileChooser;
    private javax.swing.JComboBox<String> defaultSaveTempFileChooser;
    private javax.swing.JButton determineBtn;
    private javax.swing.JRadioButton downloadedDelete;
    private javax.swing.JRadioButton downloadedForExitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton openImgByCustom;
    private javax.swing.JRadioButton reminderAfterDownloadBtn;
    private javax.swing.JButton saveAsBtn;
    private javax.swing.JButton saveTempAsBtn;
    private javax.swing.JButton setKey;
    // End of variables declaration
}
